const LANGUAGE_NORMALIZATION = {
    'arabic': 'Arabic', 'arabe': 'Arabic', 'العربية': 'Arabic', 'modern standard arabic': 'Arabic',
    'egyptian arabic': 'Arabic', 'levantine arabic': 'Arabic', 'maghrebi arabic': 'Arabic',
    'bengali': 'Bengali', 'bangla': 'Bengali', 'বাংলা': 'Bengali', 'bangla,bengali': 'Bengali',
    'bengali,hindi': 'Bengali', 'bengali,english,hindi': 'Bengali', 'chinese': 'Chinese',
    'mandarin': 'Chinese', '中文': 'Chinese', 'zhongwen': 'Chinese', 'putonghua': 'Chinese',
    'cantonese': 'Chinese', 'yue': 'Chinese', 'english': 'English', 'british english': 'English',
    'american english': 'English', 'australian english': 'English', 'canadian english': 'English', 'englsih': 'English',
    'english,spanish': 'English', 'english,hindi': 'Hindi', 'english,hindi,marathi': 'Hindi',
    'english,hindi,punjabi': 'Hindi', 'english hindi': 'Hindi', 'english,hindi,urdu': 'Hindi',
    'english,english hindi,hindi': 'Hindi', 'english,malayalam,tamil': 'Malayalam',
    'english,kannada,malayalam,tamil,telugu,urdu': 'Kannada', 'english,online radio,tamil': 'Tamil',
    'french': 'French', 'français': 'French', 'francais': 'French', 'quebec french': 'French',
    'canadian french': 'French', 'german': 'German', 'deutsch': 'German', 'high german': 'German',
    'swiss german': 'German', 'austrian german': 'German', 'hindi': 'Hindi', 'हिन्दी': 'Hindi',
    'hindustani': 'Hindi', 'hindi,english': 'Hindi', 'hindi,english assamese': 'Hindi',
    'hindi,indian': 'Hindi', 'hindi,kashmiri,urdu': 'Hindi', 'hindi,marathi': 'Hindi',
    'hindi,marathi,sanskrit': 'Hindi', 'hindi,punjabi': 'Hindi', 'hindi,telugu': 'Hindi',
    'hindi,english,hindi': 'Hindi', 'haryanvi': 'Hindi', 'haryanvi,hindi,punjabi': 'Hindi',
    'chhattisgarhi,hindi': 'Hindi', 'bhojpuri': 'Hindi', 'classical,evergreens,hindi': 'Hindi',
    'italian': 'Italian', 'italiano': 'Italian', 'japanese': 'Japanese', '日本語': 'Japanese',
    'nihongo': 'Japanese', 'korean': 'Korean', '한국어': 'Korean', 'hanguk-eo': 'Korean',
    '조선말': 'Korean', 'joseongeul': 'Korean', 'portuguese': 'Portuguese', 'português': 'Portuguese',
    'portugues': 'Portuguese', 'brazilian portuguese': 'Portuguese', 'european portuguese': 'Portuguese',
    'russian': 'Russian', 'русский': 'Russian', 'russkiy': 'Russian', 'spanish': 'Spanish',
    'español': 'Spanish', 'castilian': 'Spanish', 'castellano': 'Spanish', 'latin american spanish': 'Spanish',
    'tamil': 'Tamil', 'தமிழ்': 'Tamil', 'telugu': 'Telugu', 'తెలుగు': 'Telugu', 'urdu': 'Urdu',
    'اردو': 'Urdu', 'swahili': 'Swahili', 'kiswahili': 'Swahili', 'dutch': 'Dutch', 'nederlands': 'Dutch',
    'flemish': 'Dutch', 'afrikaans': 'Afrikaans', 'turkish': 'Turkish', 'türkçe': 'Turkish',
    'turkce': 'Turkish', 'polish': 'Polish', 'polski': 'Polish', 'vietnamese': 'Vietnamese',
    'tiếng việt': 'Vietnamese', 'tieng viet': 'Vietnamese', 'thai': 'Thai', 'ไทย': 'Thai',
    'phasa thai': 'Thai', 'greek': 'Greek', 'ελληνικά': 'Greek', 'ellinika': 'Greek', 'hebrew': 'Hebrew',
    'עברית': 'Hebrew', 'ivrit': 'Hebrew', 'persian': 'Persian', 'farsi': 'Persian', 'پارسی': 'Persian',
    'dari': 'Persian', 'malay': 'Malay', 'bahasa melayu': 'Malay', 'bahasa malaysia': 'Malay',
    'indonesian': 'Indonesian', 'bahasa indonesia': 'Indonesian', 'filipino': 'Filipino',
    'tagalog': 'Filipino', 'pilipino': 'Filipino', 'ukrainian': 'Ukrainian', 'українська': 'Ukrainian',
    'ukrayinska': 'Ukrainian', 'czech': 'Czech', 'čeština': 'Czech', 'cestina': 'Czech',
    'swedish': 'Swedish', 'svenska': 'Swedish', 'norwegian': 'Norwegian', 'norsk': 'Norwegian',
    'bokmål': 'Norwegian', 'nynorsk': 'Norwegian', 'danish': 'Danish', 'dansk': 'Danish',
    'finnish': 'Finnish', 'suomi': 'Finnish', 'hungarian': 'Hungarian', 'magyar': 'Hungarian',
    'romanian': 'Romanian', 'română': 'Romanian', 'romana': 'Romanian', 'bulgarian': 'Bulgarian',
    'български': 'Bulgarian', 'balgarski': 'Bulgarian', 'serbian': 'Serbian', 'српски': 'Serbian',
    'srpski': 'Serbian', 'croatian': 'Croatian', 'hrvatski': 'Croatian', 'slovak': 'Slovak',
    'slovenčina': 'Slovak', 'slovencina': 'Slovak', 'slovenian': 'Slovenian', 'slovenščina': 'Slovenian',
    'slovenscina': 'Slovenian', 'assamese': 'Assamese', 'gujarati': 'Gujarati', 'gujrati': 'Gujarati', 'gujarati,hindi': 'Gujarati',
    'kannada': 'Kannada', 'malayalam': 'Malayalam', 'malayalam,ml': 'Malayalam', 'malayalam,tamil': 'Malayalam',
    'marathi': 'Marathi', 'nepali': 'Nepali', 'odia': 'Odia', 'punjabi': 'Punjabi', 'sanskrit': 'Sanskrit',
    'estonian': 'Estonian', 'dan': 'Danish', 'englishish': 'English', 'konkani': 'Konkani', 'magesh': 'Marathi', 'bihari': 'Hindi', 'chhattisgarhi': 'Hindi', 'indian': 'Hindi'
};

export { LANGUAGE_NORMALIZATION };